nnoremap gd         <cmd>LspSagaDefPreview<CR>
nnoremap gD	        <cmd>LspSagaFinder<CR>
nnoremap <leader>rr <cmd>LspSagaRename<CR>
nnoremap <leader>ra <cmd>LspSagaCodeAction<CR>
xnoremap <leader>ra <cmd>LspSagaRangeCodeAction<CR>
nnoremap ]d	        <cmd>LspSagaDiagJumpNext<CR>
nnoremap [d         <cmd>LspSagaDiagJumpPrev<CR>
nnoremap ]D         <cmd>LspSagaShowLineDiags<CR>
nnoremap [D         <cmd>LspSagaShowLineDiags<CR>
