return {
  File = {
    icon = '',
    highlight = 'TSURI',
    is_symbol_kind = true,
    is_completion_kind = true,
  },
  Module = {
    icon = '',
    highlight = 'TSNamespace',
    is_symbol_kind = true,
    is_completion_kind = false,
  },
  Namespace = {
    icon = '',
    highlight = 'TSNamespace',
    is_symbol_kind = true,
    is_completion_kind = false,
  },
  Package = {
    icon = '',
    highlight = 'TSNamespace',
    is_symbol_kind = true,
    is_completion_kind = false,
  },
  Class = {
    icon = 'ﴯ',
    highlight = 'TSType',
    is_symbol_kind = true,
    is_completion_kind = true,
  },
  Text = {
    icon = '',
    highlight = 'TSText',
    is_symbol_kind = false,
    is_completion_kind = true,
  },
  Method = {
    icon = '',
    highlight = 'TSMethod',
    is_symbol_kind = true,
    is_completion_kind = true,
  },
  Property = {
    icon = '',
    highlight = 'TSMethod',
    is_symbol_kind = true,
    is_completion_kind = true,
  },
  Field = {
    icon = 'ﰠ',
    highlight = 'TSField',
    is_symbol_kind = true,
    is_completion_kind = true,
  },
  Constructor = {
    icon = '',
    highlight = 'TSConstructor',
    is_symbol_kind = true,
    is_completion_kind = true,
  },
  Unit = {
    icon = '',
    highlight = 'TSConstant',
    is_symbol_kind = false,
    is_completion_kind = true,
  },
  Value = {
    icon = '',
    highlight = 'TSConstant',
    is_symbol_kind = false,
    is_completion_kind = true,
  },
  Enum = {
    icon = '',
    highlight = 'TSType',
    is_symbol_kind = true,
    is_completion_kind = true,
  },
  Keyword = {
    icon = '',
    highlight = 'TSType',
    is_symbol_kind = false,
    is_completion_kind = true,
  },
  Snippet = {
    icon = '',
    highlight = 'RedBold',
    is_symbol_kind = false,
    is_completion_kind = true,
  },
  Color = {
    icon = '',
    highlight = 'TSConstant',
    is_symbol_kind = false,
    is_completion_kind = true,
  },
  Interface = {
    icon = '',
    highlight = 'TSType',
    is_symbol_kind = true,
    is_completion_kind = true,
  },
  Function = {
    icon = '',
    highlight = 'TSFunction',
    is_symbol_kind = true,
    is_completion_kind = true,
  },
  Variable = {
    icon = '',
    highlight = 'TSConstant',
    is_symbol_kind = true,
    is_completion_kind = true,
  },
  Constant = {
    icon = '',
    highlight = 'TSConstant',
    is_symbol_kind = true,
    is_completion_kind = true,
  },
  String = {
    icon = 'ﳳ',
    highlight = 'TSString',
    is_symbol_kind = true,
    is_completion_kind = false,
  },
  Number = {
    icon = '',
    highlight = 'TSNumber',
    is_symbol_kind = true,
    is_completion_kind = false,
  },
  Boolean = {
    icon = '',
    highlight = 'TSBoolean',
    is_symbol_kind = true,
    is_completion_kind = false,
  },
  Array = {
    icon = '',
    highlight = 'TSConstat',
    is_symbol_kind = true,
    is_completion_kind = false,
  },
  Object = {
    icon = '',
    highlight = 'TSType',
    is_symbol_kind = true,
    is_completion_kind = false,
  },
  Key = {
    icon = '',
    highlight = 'TSType',
    is_symbol_kind = true,
    is_completion_kind = false,
  },
  Null = {
    icon = 'ﳠ',
    highlight = 'TSType',
    is_symbol_kind = true,
    is_completion_kind = false,
  },
  Reference = {
    icon = '',
    highlight = 'TSTextReference',
    is_symbol_kind = false,
    is_completion_kind = true,
  },
  Folder = {
    icon = '',
    highlight = 'TSURI',
    is_symbol_kind = false,
    is_completion_kind = true,
  },
  EnumMember = {
    icon = '',
    highlight = 'TSField',
    is_symbol_kind = true,
    is_completion_kind = true,
  },
  Struct = {
    icon = '',
    highlight = 'TSType',
    is_symbol_kind = true,
    is_completion_kind = true,
  },
  Event = {
    icon = '',
    highlight = 'TSType',
    is_symbol_kind = true,
    is_completion_kind = true,
  },
  Operator = {
    icon = '璉',
    highlight = 'TSOperator',
    is_symbol_kind = true,
    is_completion_kind = true,
  },
  TypeParameter = {
    icon = '',
    highlight = 'TSParameter',
    is_symbol_kind = true,
    is_completion_kind = true,
  },
}
