return {
  File = {
    icon = '',
    highlight = '@text.uri',
    is_symbol_kind = true,
    is_completion_kind = true,
  },
  Module = {
    icon = '',
    highlight = '@namespace',
    is_symbol_kind = true,
    is_completion_kind = false,
  },
  Namespace = {
    icon = '',
    highlight = '@namespace',
    is_symbol_kind = true,
    is_completion_kind = false,
  },
  Package = {
    icon = '',
    highlight = '@namespace',
    is_symbol_kind = true,
    is_completion_kind = false,
  },
  Class = {
    icon = 'ﴯ',
    highlight = '@type',
    is_symbol_kind = true,
    is_completion_kind = true,
  },
  Text = {
    icon = '',
    highlight = '@text',
    is_symbol_kind = false,
    is_completion_kind = true,
  },
  Method = {
    icon = '',
    highlight = '@method',
    is_symbol_kind = true,
    is_completion_kind = true,
  },
  Property = {
    icon = '',
    highlight = '@property',
    is_symbol_kind = true,
    is_completion_kind = true,
  },
  Field = {
    icon = 'ﰠ',
    highlight = '@field',
    is_symbol_kind = true,
    is_completion_kind = true,
  },
  Constructor = {
    icon = '',
    highlight = '@constructor',
    is_symbol_kind = true,
    is_completion_kind = true,
  },
  Unit = {
    icon = '',
    highlight = 'TSConstant',
    is_symbol_kind = false,
    is_completion_kind = true,
  },
  Value = {
    icon = '',
    highlight = '@constant',
    is_symbol_kind = false,
    is_completion_kind = true,
  },
  Enum = {
    icon = '',
    highlight = '@type',
    is_symbol_kind = true,
    is_completion_kind = true,
  },
  Keyword = {
    icon = '',
    highlight = '@keyword',
    is_symbol_kind = false,
    is_completion_kind = true,
  },
  Snippet = {
    icon = '',
    highlight = 'RedBold',
    is_symbol_kind = false,
    is_completion_kind = true,
  },
  Color = {
    icon = '',
    highlight = '@constant',
    is_symbol_kind = false,
    is_completion_kind = true,
  },
  Interface = {
    icon = '',
    highlight = '@type',
    is_symbol_kind = true,
    is_completion_kind = true,
  },
  Function = {
    icon = '',
    highlight = '@function',
    is_symbol_kind = true,
    is_completion_kind = true,
  },
  Variable = {
    icon = '',
    highlight = '@constant',
    is_symbol_kind = true,
    is_completion_kind = true,
  },
  Constant = {
    icon = '',
    highlight = '@constant',
    is_symbol_kind = true,
    is_completion_kind = true,
  },
  String = {
    icon = 'ﳳ',
    highlight = '@string',
    is_symbol_kind = true,
    is_completion_kind = false,
  },
  Number = {
    icon = '',
    highlight = '@number',
    is_symbol_kind = true,
    is_completion_kind = false,
  },
  Boolean = {
    icon = '',
    highlight = '@boolean',
    is_symbol_kind = true,
    is_completion_kind = false,
  },
  Array = {
    icon = '',
    highlight = '@constant',
    is_symbol_kind = true,
    is_completion_kind = false,
  },
  Object = {
    icon = '',
    highlight = '@type',
    is_symbol_kind = true,
    is_completion_kind = false,
  },
  Key = {
    icon = '',
    highlight = '@type',
    is_symbol_kind = true,
    is_completion_kind = false,
  },
  Null = {
    icon = 'ﳠ',
    highlight = '@type',
    is_symbol_kind = true,
    is_completion_kind = false,
  },
  Reference = {
    icon = '',
    highlight = '@text.reference',
    is_symbol_kind = false,
    is_completion_kind = true,
  },
  Folder = {
    icon = '',
    highlight = '@text.uri',
    is_symbol_kind = false,
    is_completion_kind = true,
  },
  EnumMember = {
    icon = '',
    highlight = '@field',
    is_symbol_kind = true,
    is_completion_kind = true,
  },
  Struct = {
    icon = '',
    highlight = '@type',
    is_symbol_kind = true,
    is_completion_kind = true,
  },
  Event = {
    icon = '',
    highlight = '@type',
    is_symbol_kind = true,
    is_completion_kind = true,
  },
  Operator = {
    icon = '璉',
    highlight = '@operator',
    is_symbol_kind = true,
    is_completion_kind = true,
  },
  TypeParameter = {
    icon = '',
    highlight = '@parameter',
    is_symbol_kind = true,
    is_completion_kind = true,
  },
}
