highlight! link LspTroubleCount           RedBackgroundContrast
highlight! link LspTroubleFile            BlueBold
highlight! link LspTroubleIndent          WhiteBold
highlight! link LspTroubleFoldIcon        WhiteBold
highlight! link LspTroubleText            White
highlight! link LspTroubleSource          GreyItalic
highlight! link LspTroubleCode            GreyBold
highlight! link LspTroubleLocation        WhiteItalic
highlight! link LspTroublePreview         OrangeBackgroundContrast
