("===" @binary_expression (set! conceal "≡"))
("==" @binary_expression (set! conceal "≡"))
("!=" @binary_expression (set! conceal "≢"))
("<=" @binary_expression (set! conceal "≤"))
(">=" @binary_expression (set! conceal "≥"))
