vim.api.nvim_set_hl(0, 'NeoTreeIndentMarker', { link = 'Grey' })
vim.api.nvim_set_hl(0, 'NeoTreeFileName', { link = 'White' })
vim.api.nvim_set_hl(0, 'NeoTreeFileNameOpened', { link = 'WhiteBold' })
vim.api.nvim_set_hl(0, 'NeoTreeDirectoryIcon', { link = 'LightGrey' })
vim.api.nvim_set_hl(0, 'NeoTreeDirectoryName', { link = 'White' })

-- Wtf
vim.api.nvim_set_hl(0, 'NeoTreeGitAdded', { link = 'Green' })
vim.api.nvim_set_hl(0, 'NeoTreeGitConflict', { link = 'RedBold' })
vim.api.nvim_set_hl(0, 'NeoTreeGitDeleted', { link = 'Red' })
vim.api.nvim_set_hl(0, 'NeoTreeGitIgnored', { link = 'GreyUnderline' })
vim.api.nvim_set_hl(0, 'NeoTreeGitModified', { link = 'Blue' })
vim.api.nvim_set_hl(0, 'NeoTreeGitRenamed', { link = 'BlueUnderline' })
vim.api.nvim_set_hl(0, 'NeoTreeGitStaged', { link = 'LightGrey' })
vim.api.nvim_set_hl(0, 'NeoTreeGitUntracked', { link = 'Yellow' })
vim.api.nvim_set_hl(0, 'NeoTreeGitUnstaged', { link = 'Normal' })

vim.api.nvim_set_hl(0, 'NeoTreeTabActive', { link = 'GreyBackground' })
vim.api.nvim_set_hl(0, 'NeoTreeTabSeparatorActive', { link = 'Grey' })
vim.api.nvim_set_hl(0, 'NeoTreeTabInactive', { link = 'DarkGreyBackground' })
vim.api.nvim_set_hl(0, 'NeoTreeTabSeparatorInactive', { link = 'DarkGrey' })
