-- return function()
--   require("lsp.start")({
--     name = 'SonarLint',
--     cmd = {
--       'sonarlint-ls',
--       '-stdio',
--       '-analyzers',
--       '/usr/share/java/sonarlint-ls/analyzers/sonarjava.jar',
--     },
--     root_dir = vim.fs.root(0, { 'build.gradle', 'build.gradle.kts' }),
--   })
-- end
