highlight! link RegistersPrefixSeparator WhiteBold
highlight! link RegistersPrefixYank OrangeBold
highlight! link RegistersPrefixHistory BlueBold
highlight! link RegistersPrefixSelection RedBold
highlight! link RegistersPrefixDefault YellowBold
highlight! link RegistersPrefixUnnamed WhiteBold
highlight! link RegistersPrefixReadOnly PurpleBold
highlight! link RegistersPrefixLastSearch BlackBold
highlight! link RegistersPrefixNamed GreenBold
